version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: backend
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"

  backend:
    image: ghcr.io/zypcon/auto-curtain-backend:latest
    container_name: private-store-autocurtain_backend_1
    restart: on-failure
    depends_on:
      - mosquitto
    volumes:
      - ${APP_DATA_DIR}/data/backend:/app/data
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - MQTT_USERNAME=$APP_AUTOCURTAIN_MQTT_USERNAME
      - MQTT_PASSWORD=$APP_AUTOCURTAIN_MQTT_PASSWORD
      - DATABASE_PATH=/app/data/vorhang.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1

  mosquitto:
    image: ghcr.io/zypcon/auto-curtain-mosquitto:latest
    container_name: private-store-autocurtain_mosquitto_1
    restart: on-failure
    ports:
      - "1883:1883"
    volumes:
      - ${APP_DATA_DIR}/data/mosquitto/secrets:/mosquitto/secrets
      - ${APP_DATA_DIR}/data/mosquitto/data:/mosquitto/data
